GRANT ALL 
ON *
TO fred IDENTIFIED BY 'mnb123'
WITH GRANT OPTION;

GRANT USAGE
ON books.*
TO sally IDENTIFIED BY 'magic123';

GRANT SELECT, INSERT, UPDATE, DELETE, INDEX, ALTER, CREATE, DROP, 
ON books.*
TO sally;
